### ISSUE TITLE
Can you change it to a remote zip URL?

### ISSUE THREAD

**Issue by gwuluo** [YahnisElsts/wp-update-server#115]
/packages Can the folder be changed to the s3 zip url?
What do I need to rewrite, 
Thanks for your help.

**Comment by YahnisElsts** [comment]
Completely getting rid of `packages` would be difficult. However, if you're okay with just changing the download URL, you could subclass `Wpup_UpdateServer` and override the [`filterMetadata()` method](https://github.com/YahnisElsts/wp-update-server/blob/74fe540e2a70cfc559376bd83a7f4447ffa998d9/includes/Wpup/UpdateServer.php#L245).

For example, something like this:
```php
protected function filterMetadata($meta, $request) {
    $meta = parent::filterMetadata($meta, $request);
    $meta['download_url'] = generateS3ZipUrlFromSlug($request->slug);
    return $meta;
}
```

You would still need to have the ZIP files in the `packages` folder, too, so that the update server can extract metadata like the version number and changelog from them.

**Comment by gwuluo** [comment]
Thanks for the reply, I'll give it a try. Thank you.
