### ISSUE TITLE
download link access denied

### ISSUE THREAD

**Issue by sepano** [YahnisElsts/wp-update-server#42]
Hi 
I installed this script and added my plugin. so that i should see something in this two endpoints:
metadata: http://plugins.appchar.com/?action=get_metadata&slug=appchar
download: http://plugins.appchar.com/php5-fcgi?action=download&slug=appchar

Metadata works fine but download link returns "access denied". 
I found this in apache error log: 

`[Mon Aug 08 15:49:45.592131 2016] [:error] [pid 32371:tid 140625072580352] [client 37.255.134.131:10853] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: Access to the script '/usr/lib/cgi-bin/php5-fcgi' has been denied (see security.limit_extensions)
`

It is not folder/file permision issue
help please

**Comment by YahnisElsts** [comment]
It sounds like the script incorrectly guesses the server URL because FastCGI doesn't set the correct `SCRIPT_NAME`. [Possibly relevant SO question.](http://stackoverflow.com/questions/21265469/php-serverscript-name-is-wrong-when-loading-php-via-mod-fcgid)

The easiest workaround would probably be to set the server URL directly so that the script doesn't need to guess. You can do that by changing the third line in index.php to this:

```php
$server = new Wpup_UpdateServer('http://plugins.appchar.com/');
```

**Comment by sepano** [comment]
Same Error
also i tried this:
`$server` = new Wpup_UpdateServer('http:\/\/plugins.appchar.com\/');

And nothing changed

**Comment by YahnisElsts** [comment]
Please check again. The `download_url` field in the metadata has changed and now the download works correctly. The new URL is:
http://plugins.appchar.com/?action=download&slug=appchar

**Comment by sepano** [comment]
You are correct. 
The link is changed.

thanks for your help.

**Comment by YahnisElsts** [comment]
All right, I'm glad to heard it worked.
