### ISSUE TITLE
Updated theme and validating a "key"

### ISSUE THREAD

**Issue by d4b** [YahnisElsts/wp-update-server#49]
I followed this [post](http://w-shadow.com/blog/2013/03/19/plugin-updates-securing-download-links/)! And everything works ok, except: 

```
require get_template_directory() . '/admin/theme-updates/plugin-update-checker/plugin-update-checker.php';
$UpdateChecker = Puc_v4_Factory::buildUpdateChecker(
    'http://dev/wp-update-server/?action=get_metadata&slug=theme_name',
    __FILE__,
    'theme_name'
);

//Add the license key to query arguments.
$UpdateChecker->addQueryArgFilter('wsh_filter_update_checks');
function wsh_filter_update_checks($queryArgs) {
    $settings = get_option('license_key');
    $queryArgs['license_key'] = $settings;
    return $queryArgs;
}
```

Result:
Downloading update from http://dev/wp-update-server/?action=download&slug=theme&license_key=totallyvalid…
An error occurred while updating Theme: Download failed. Forbidden

What else must be added to functions.php?

**Comment by YahnisElsts** [comment]
You don't need to add anything more to functions.php. Based on the error message, what you need to do is verify that the update server handles the license key correctly.

Does the update download link work if you open it in the browser? If not, double-check your license validation code. Unfortunately, I can't offer any more specific suggestions because I don't know what that part of your implementation is like.

**Comment by d4b** [comment]
You can directly download the file without any problem. Validation also works without a problem

**Comment by YahnisElsts** [comment]
Did you figure out what was wrong? If it's something that could affect other users of this library, please let me know.
